AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Starts the test slaves.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs8.10
    Environment:
      Variables: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
          NODE_ENV: development

Resources:

    provisionAppSlaves:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./app-slave-provisioner
            Handler: index.provisionAppSlaves

    provisionSeleniumHubNodes:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./selenium-hub-nodes-provisioner
            Handler: index.provisionSeleniumHubNodes

Outputs:

  provisionAppSlaves:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt provisionAppSlaves.Arn

  provisionAppSlavesIamRole:
    Description: "Implicit IAM Role created for provisionAppSlaves function"
    Value: !GetAtt provisionAppSlavesRole.Arn
